"""auth: names, oauth provider, nullable password

Revision ID: 6b2d2acf08ec
Revises: 904322af6e1b
Create Date: 2026-07-14 11:38:27.506319
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b2d2acf08ec'
down_revision: Union[str, None] = '904322af6e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
