"""initial schema

Revision ID: 904322af6e1b
Revises: 
Create Date: 2026-07-02 13:55:25.618573
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '904322af6e1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plans',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('product_limit', sa.Integer(), nullable=True),
    sa.Column('ai_monthly_quota', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('designer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('portfolio_state', sa.Enum('LIVE', 'DRAFT', name='storestate'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_designer_profiles_slug'), 'designer_profiles', ['slug'], unique=True)
    op.create_table('designs',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'PAID', name='designtype'), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'AI', name='designsource'), nullable=False),
    sa.Column('resource_url', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('SALE', 'NEW_BID', 'BID_ACCEPTED', 'COLLAB_UPDATE', 'NEW_PRODUCTION_ORDER', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_details',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('printshop_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('seller_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('store_state', sa.Enum('LIVE', 'DRAFT', name='storestate'), nullable=False),
    sa.Column('plan_code', sa.Enum('FREE', 'CREATOR', 'PRO', name='plancode'), nullable=False),
    sa.Column('ai_credits_balance', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_seller_profiles_slug'), 'seller_profiles', ['slug'], unique=True)
    op.create_table('settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('receive_newsletters', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('social_links',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', 'YOUTUBE', 'TIKTOK', 'X', 'OTHER', name='socialplatform'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('BUYER', 'SELLER', 'DESIGNER', 'PRINTSHOP', name='role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_table('ai_credit_transactions',
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('PLAN_GRANT', 'AI_GENERATION', 'ADDON', name='aicreditreason'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_items',
    sa.Column('print_shop_profile_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['print_shop_profile_id'], ['printshop_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('buyer_user_id', sa.Uuid(), nullable=False),
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designer_calls',
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('brief', sa.String(), nullable=False),
    sa.Column('reference_image_url', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_type', sa.Enum('FIXED', 'PERCENT', 'BOTH', name='paymenttype'), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'AWARDED', 'CLOSED', name='callstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('buyer_user_id', sa.Uuid(), nullable=False),
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FULFILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seller_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_item_variants',
    sa.Column('base_item_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_item_id'], ['base_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('designer_profile_id', sa.Uuid(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='bidstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['designer_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['designer_profile_id'], ['designer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_areas',
    sa.Column('base_item_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_item_id'], ['base_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_options',
    sa.Column('base_item_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('MATERIAL', 'PRINT_TYPE', name='printoptionkind'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_item_id'], ['base_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_items',
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('base_item_id', sa.Uuid(), nullable=False),
    sa.Column('design_id', sa.Uuid(), nullable=True),
    sa.Column('print_area_id', sa.Uuid(), nullable=True),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('state', sa.Enum('LISTED', 'UNLISTED', 'PENDING', name='shopitemstate'), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('only_followers', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_item_id'], ['base_items.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['print_area_id'], ['print_areas.id'], ),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('shop_item_id', sa.Uuid(), nullable=False),
    sa.Column('base_item_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_item_variant_id'], ['base_item_variants.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborations',
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('seller_profile_id', sa.Uuid(), nullable=False),
    sa.Column('designer_profile_id', sa.Uuid(), nullable=False),
    sa.Column('agreed_price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'PREVIEW', 'PREVIEW_ACCEPTED', 'FINAL', 'FINAL_ACCEPTED', 'PAYMENT', 'COMPLETED', name='collabstate'), nullable=False),
    sa.Column('shop_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['designer_calls.id'], ),
    sa.ForeignKeyConstraint(['designer_profile_id'], ['designer_profiles.id'], ),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('shop_item_id', sa.Uuid(), nullable=False),
    sa.Column('base_item_variant_id', sa.Uuid(), nullable=False),
    sa.Column('print_shop_profile_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fulfillment_status', sa.Enum('PAID', 'IN_PRODUCTION', 'HANDED_TO_SHIPMENT', name='fulfillmentstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['base_item_variant_id'], ['base_item_variants.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['print_shop_profile_id'], ['printshop_profiles.id'], ),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('collab_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collab_submissions',
    sa.Column('collab_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('PREVIEW', 'FINAL', name='submissionkind'), nullable=False),
    sa.Column('design_id', sa.Uuid(), nullable=True),
    sa.Column('resource_url', sa.String(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='submissiondecision'), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collab_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collab_submissions')
    op.drop_table('chat_messages')
    op.drop_table('order_items')
    op.drop_table('collaborations')
    op.drop_table('cart_items')
    op.drop_table('shop_items')
    op.drop_table('print_options')
    op.drop_table('print_areas')
    op.drop_table('bids')
    op.drop_table('base_item_variants')
    op.drop_table('orders')
    op.drop_table('designer_calls')
    op.drop_table('carts')
    op.drop_table('base_items')
    op.drop_table('ai_credit_transactions')
    op.drop_table('user_roles')
    op.drop_table('social_links')
    op.drop_table('settings')
    op.drop_index(op.f('ix_seller_profiles_slug'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_table('printshop_profiles')
    op.drop_table('payout_details')
    op.drop_table('notifications')
    op.drop_table('designs')
    op.drop_index(op.f('ix_designer_profiles_slug'), table_name='designer_profiles')
    op.drop_table('designer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
